sudo: required
services:
  - docker

before_install:
  - docker build -t karthikjag/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true karthikjag/react-test npm run test

after_success:
  - docker build -t karthikjag/complex-nginx ./nginx
  - docker build -t karthikjag/complex-client ./client
  - docker build -t karthikjag/complex-server ./server
  - docker build -t karthikjag/complex-worker ./worker
  # docker CLI login
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  # push images to docker hub
  - docker push karthikjag/complex-client
  - docker push karthikjag/complex-ngnix
  - docker push karthikjag/complex-server
  - docker push karthikjag/complex-worker
  